---
language: python
python: "3.5.3"

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.2.2.0
  - ANSIBLE_VERSION=2.2.1.0
  - ANSIBLE_VERSION=2.2.0.0
 # - ANSIBLE_VERSION=2.1.5
 # - ANSIBLE_VERSION=2.1.4
 # - ANSIBLE_VERSION=2.1.3
 # - ANSIBLE_VERSION=2.1.2

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i test/inventory test/test.yml --syntax-check
  
  #- ansible-playbook -i test/inventory test/test.yml --connection=local --sudo
  
  # Idempotence test WIP
  #- "ansible-playbook -i test/inventory test/test.yml --connection=local --sudo | tee /tmp/output.txt; grep -q 'changed=0.*failed=0' /tmp/output.txt &amp;&amp; (echo 'Idempotence test: pass' &amp;&amp; exit 0) || (echo 'Idempotence test: fail' &amp;&amp; exit 1)"

  # check if the prometheus was created

  - if [ grep -q prometheus -Ri /etc/passwd]; then echo "user exists!"; else echo "user does not exist!"; fi
  
  # Request a page via the web server, to make sure it's running and responds.
  - curl -v http://localhost:9090
