---
- name: reload_systemd
  command: systemctl daemon-reload
  become: yes

- name: restart_prometheus
  service:
    name: prometheus
    state: restarted
    enabled: yes
  become: yes

- name: restart_alertmanager
  service:
    name: alertmanager
    state: restarted
    enabled: yes
  become: yes
