- name: create alertmanager directory structure
  file:
    state: directory
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    mode: 0755
  with_items:
    - "{{ alertmanager_root_dir }}"
    - "{{ alertmanager_bin_dir }}"
    - "{{ alertmanager_dist_dir }}"
    - "{{ alertmanager_config_dir }}"
  become: yes

- name: install alertmanager
  unarchive:
    src: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: "{{ alertmanager_dist_dir }}"
    remote_src: True
    owner: prometheus
    group: prometheus
  become: yes

- file:
    src: "{{ alertmanager_dist_dir}}/alertmanager-{{alertmanager_version}}.linux-amd64"
    dest: "{{alertmanager_server_dir}}"
    owner: prometheus
    group: prometheus
    state: link
  become: yes

- name: create alertmanager config file
  template:
    src: alertmanager.yml
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
  become: yes
  notify:
    - restart_alertmanager

- name: Add alertmanager.service
  template:
    src: alertmanager-service.ini
    dest: /lib/systemd/system/alertmanager.service
    mode: 0644
  become: yes
  notify:
    - reload_systemd
    - restart_prometheus
    - restart_alertmanager
