---

- name: create prometheus user
  user:
    name: prometheus
    comment: prometheus
    shell: /usr/sbin/nologin
    home: /opt/prometheus
  become: yes

- name: create prometheus directory structure
  file:
    state: directory
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    mode: 0755
  with_items:
    - "{{ prometheus_root_dir }}"
    - "{{ prometheus_bin_dir }}"
    - "{{ prometheus_dist_dir }}"
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_db_dir }}"
  become: yes

- name: install prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "{{ prometheus_dist_dir }}"
    remote_src: True
    owner: prometheus
    group: prometheus
  become: yes

- file:
    src: "{{ prometheus_dist_dir }}/prometheus-{{prometheus_version}}.linux-amd64"
    dest: "{{prometheus_server_dir}}"
    owner: prometheus
    group: prometheus
    state: link
  become: yes

- name: create prometheus config file
  template:
    src: prometheus.yml
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
  become: yes
  notify:
    - restart_prometheus

- name: Add prometheus.service
  template:
    src: prometheus-service.ini
    dest: /lib/systemd/system/prometheus.service
    mode: 0644
  become: yes
  notify:
    - reload_systemd
    - restart_prometheus
