---

- name: get current prometheus version
  command: "{{ prometheus_server_dir }}/prometheus -version"
  register: prometheus_current
  ignore_errors: yes

- name: get current alertmanager version
  command: "{{ alertmanager_server_dir }}/alertmanager -version"
  register: alertmanager_current
  ignore_errors: yes


- name: install prometheus
  include: install-prometheus.yml
  when: prometheus_current.rc != 0 or not prometheus_current.stdout | search(prometheus_version_string_match)

- name: install alertmanager
  include: install-alertmanager.yml
  when: alertmanager_current.rc != 0 or not alertmanager_current.stdout | search(alertmanager_version_string_match)
